### ISSUE TITLE
Package status is stopped, but it is running. Cannot stop it!

### ISSUE THREAD

**Issue by yulbeast** [colin1497/Synology-Install-Package-for-Minecraft-and-Craftbukkit#11]
DMS 6
I installed the package. It starts, but the package center identifies it as stopped. Actions offered are run and uninstall.
I think it is running because if I try to connect to it from a client, I see the try in the log (well, I'm having user disconected problem, but this is another issue).

How can I stop it from console?

**Comment by yulbeast** [comment]
forget it, I found this on the internet, and seems to work:
sudo /usr/syno/bin/synopkg stop Minecraft

Anyway, I think the package status is not right at the gui

**Comment by colin1497** [comment]
I'm having a similar issue under DSM 6 now that I've finally upgraded my box.  Working on it.

**Comment by colin1497** [comment]
Build 0026 works. Manfred Stumpf had a simple change that fixed the status reporting issue.
