### ISSUE TITLE
world recovery

### ISSUE THREAD

**Issue by bwcomputing** [colin1497/Synology-Install-Package-for-Minecraft-and-Craftbukkit#13]
hello and a great thank for the minecraft package for synology, 
my level in java development is very poor and a have a trouble recently after a DSM upgrade.
after the craftbukkit and minecraft shutdown during the DSM upgrade, when i get connected to the server after the upgrade, i lost completely my precedent world.
I have finally found the data in the world folder an copy this in a local folder,
The ancient wold work fine in solo mode on local, but a have not successfully achieve the copy on the server. 
is there a procedure to achieve a functional copy of the ancient data world ?
thank a lot in advance,
JP

**Comment by colin1497** [comment]
I'm afraid I haven't experienced this and don't have any more information.  I think it's related to https://github.com/colin1497/Synology-Install-Package-for-Minecraft-and-Craftbukkit/issues/19 but I don't lose my world when I upgrade, only json files.  I'm going to close this and hopefully we can close it with https://github.com/colin1497/Synology-Install-Package-for-Minecraft-and-Craftbukkit/issues/19.
