### ISSUE TITLE
Reinstalled package under user "minecraft" does not allow any editing

### ISSUE THREAD

**Issue by drodrigz** [colin1497/Synology-Install-Package-for-Minecraft-and-Craftbukkit#14]
Hi there.
I recently had to reinstall the server in my DS916+ and after successfully installing it I was unable to change the server properties, or modify the world or nothing. I used WinSCP to log into the DS and still was unable to change anything (rewrite, save or even change permissions).  I then realized that the "Minecraft" folder in @appstore was created under the user "minecraft" and not "root", thus not allowing me to have any permissions.
Did something changed? I was able to change and edit files previously.
Please let us know if there is a way to edit files owned by "minecraft" in the server.

![minecraft_appstore](https://cloud.githubusercontent.com/assets/26159028/23541465/5d2d2292-ff9c-11e6-9b11-8994c4ecfea4.JPG)

Thanks!

**Comment by brebtatv** [comment]
Yes, I also have this problem. Please help with a solution.

**Comment by colin1497** [comment]
I think that you'll find that newer versions of Synology's DSM OS lock things down further and that you will need to "sudo su" in order to edit things.  I mention this on the blog post, including how to work around it.
