### ISSUE TITLE
Spigot and Bukkit don't work.

### ISSUE THREAD

**Issue by danielriege** [colin1497/Synology-Install-Package-for-Minecraft-and-Craftbukkit#17]
The Minecraft Server is working perfectly but the Spigot and or the Craftbukkit Server won't start after installing. The Package is running but the Server doesn't start.

**Comment by danielriege** [comment]
for example the spigot.jar file in the @appstore/Spigot folder is a text file saying to download a specific .jar file.

**Comment by danielriege** [comment]
Found a workaround. You have to replace the spigot.jar with the latest Yves Mirror spigot.jar and execute the spigot.jar by your one one the server. This will start the Minecraft Spigot Server.

**Comment by danielriege** [comment]
There has to be a problem with the source file of Spigot.

**Comment by colin1497** [comment]
This was a problem for a while but it seems to be more stable now.
