### ISSUE TITLE
Unsuccessful package installation (source problem)

### ISSUE THREAD

**Issue by e-jack** [colin1497/Synology-Install-Package-for-Minecraft-and-Craftbukkit#18]
Hello,

Again is a problem with the source file of Spigot and others.
Please update it. My childs miss for the spigot server ;)
Have you possibility to protect the source on different server to avoid similar situation in future ?

Thank you for you work and support this project.

**Comment by colin1497** [comment]
I specifically use the the public sources.  I don't want to be in the business of maintaining local copies.
