### ISSUE TITLE
Permissions on stdin.minecraft

### ISSUE THREAD

**Issue by colin1497** [colin1497/Synology-Install-Package-for-Minecraft-and-Craftbukkit#2]
From #1 

"The first time I run the server as ROOT, then I changed minecraft folder owner's to minecraft user.

I noticed that minecraft daemon can not access to the /tmp/stdin.minecraft file."

Checking on my Rackstation, I see that permissions are set as follows:

drwxr-xr-x    5 minecraf root          4096 Aug 14 18:25 Minecraft

-rw-r--r--    1 minecraf users            0 Aug 15 11:26 stdin.minecraft

Can you confirm yours?

**Comment by avluis** [comment]
Just wanted to chime in;
In a DS1513+ with DSM 6.0-7321 Update 6, afters installing 1.9.2-0026, I have:

`drwxr-xr-x  4 minecraft root 4096 May  7 18:02 Minecraft`

`-rw-r--r--  1 minecraft       users                0 May  7 18:02 stdin.minecraft`
