### ISSUE TITLE
Squawk this if they've patched and I've slept through updating.

### ISSUE THREAD

**Issue by Rusti-gotrage** [colin1497/Synology-Install-Package-for-Minecraft-and-Craftbukkit#22]
Just wondering if there are plans for a 1.14 update soon?
Also wondering if you got any further on the auto-update idea??

- Cheers!

**Comment by RKANOTAI** [comment]
> Just wondering if there are plans for a 1.14 update soon?
> Also wondering if you got any further on the auto-update idea??
> 
> * Cheers!

Hey there,by any chance did you find anything for 1.14 on syno ?

**Comment by Rusti-gotrage** [comment]
AARRGGHH!!!
It was updated for 2 whole days - then they push out 1.14.2, and now it's out of date again!!
*sobs*

**Comment by colin1497** [comment]
Sorry, Fortnite has taken over our house so hard I'm not getting notifications from my son when it goes out of date.  I'll roll up an update today.

**Comment by colin1497** [comment]
Just pushed the updated files to the distro.  Enjoy, folks.

**Comment by Rusti-gotrage** [comment]
Evening Colin!!
They've updated to 1.14.3.....

Squawk!! :)

(BTW - LOVE your style!) 🥇

**Comment by Rusti-gotrage** [comment]
* Hopes we've not lost Colin to Fortnite *

.......squawk....?   ;)

**Comment by Rusti-gotrage** [comment]
Squaaaaaaawwwkk.....?

*sob*
