### ISSUE TITLE
Install does not complete correctly

### ISSUE THREAD

**Issue by wifisher** [colin1497/Synology-Install-Package-for-Minecraft-and-Craftbukkit#23]
The install has been broken for a while. I haven't reported it because I hadn't had time to track down this GitHub repository.

I used to have it install on my DS412+ that is currently running DSM 6.2.1-23824 Update 6.

I saw the update come through so I thought that I would try it. I uninstalled the version I had installed to start fresh.

I have http://www.hildinger.us/sspks in my Package Sources and installed version 1.14.2-0038.

The Package Center thinks that Minecraft is running, but clients cannot connect to the Minecraft server.

Running "ps -ax" on the DS412+ shows the following related programs running:

```
/bin/sh /var/packages/Minecraft/scripts/launcher.sh start minecraft 
tail -n 0 -f /tmp/stdin.minecraft

```

The related section from the /var/log/synopkg.log file is attached:
[synopkg.log](https://github.com/colin1497/Synology-Install-Package-for-Minecraft-and-Craftbukkit/files/3233112/synopkg.log)

The most obvious issue is that /volume1/@appstore/Minecraft/minecraft.jar is not available. Indeed, /volume1/@appstore/Minecraft/ only contains eula.txt.

Looking at the log, it looks like the install script downloads **server.jar**, and then looks to move the file /volume1/@tmp/**minecraft***.jar somewhere. Looking in /volume1/@tmp/ I do see a server.jar file, so my guess is that the install script uses the wrong file name.

It looks like there may be other issues in the log as well, but I don't know if they are critical issues or not. The missing JAR file is critical though.

**Comment by colin1497** [comment]
Thanks for pointing this out, I've completely missed this because I've been running Spigot here, but sure enough, all I have is EULA.TXT in my /minecraft directory.

**Comment by TWV-GIT** [comment]
Hey Colin, massively appreciate your work.
Do you have an idea when this issue might get fixed?

Grtz.

**Comment by mrmorden74** [comment]
Hi,
same problem here,
i'm using a synology DS916+ with DSm version DSM 6.2.2-24922 Update 4.

After making an update of Mincraft, Spiggot and Craftbukkit work fine, but in the pure mincraft version I have only the eula.txt

Any ideas
best Alex
