### ISSUE TITLE
....Any sign of an update...?

### ISSUE THREAD

**Issue by Rusti-gotrage** [colin1497/Synology-Install-Package-for-Minecraft-and-Craftbukkit#25]
Hi Colin,

just wondering if there's any chance of an update any time soon?
Would also be happy to take over if you could do a how-to on how to update the package?

I know real life interferes... 

Cheers!

- Rusti

**Comment by colin1497** [comment]
I'll do it by this weekend.  I took a new position this summer and I've kind of been ignoring this, but I'll pull it together this week.
