### ISSUE TITLE
Craftbukkit mirror download path has changed

### ISSUE THREAD

**Issue by rieva** [colin1497/Synology-Install-Package-for-Minecraft-and-Craftbukkit#6]
Hi,

I just tried to install the Craft Bukkit package, but it fails to find the download path. It seems that the path has been changed from
https://tcpr.ca/download/craftbukkit to
https://tcpr.ca/downloads/craftbukkit

Also, I noticed that a https://tcpr.ca/downloads/craftbukkit/craftbukkit-latest.jar exists, effectively being the latest version on the mirror. (1.8.8 currently)

Is installing the original Minecraft package from your repository a precondition for the Craft Bukkit to run?

Thanks a bunch for your effort in this!

**Comment by colin1497** [comment]
Thanks for the info.  I am updating the craftbukkit package right now to include this updated link.

I linked directly to the 1.8.8 build instead of the "latest" build.  I don't know that always grabbing the latest version on something like that is wise.
