### ISSUE TITLE
Cannot complete install on DSM 6 beta

### ISSUE THREAD

**Issue by avluis** [colin1497/Synology-Install-Package-for-Minecraft-and-Craftbukkit#8]
Hey there - I know I'm bringing up an issue in regards to beta software but just wanted to give the heads up.
Synology may have changed, as always, a few things in regards to the user home service - or at least the way this package is detecting that.

At the moment, the install will not complete as it throws the error:

"Failed to install Minecraft Server.
The User Home Service is not enabled..."

User home service is enabled, but whatever Synology changed in DSM 6 (I have DSM 6.0-7274 or 6.0 beta 2) is causing this issue.
Are there any steps I can take in order to work around this?

**Comment by nucky25** [comment]
change the installer.sh file and replace the user home section by this:

#is the User Home service enabled?
  UH_SERVICE=maybe
  UH_SERVICE=`synogetkeyvalue /etc/synoinfo.conf userHomeEnable`

  if [ ${UH_SERVICE} == "no" ]; then
    echo "The User Home service is not enabled. Please enable this feature in the User control panel in DSM."
    exit 1
  fi

**Comment by avluis** [comment]
Awesome - thank you for sharing.
I installed DSM 6.0 RC so I'll report back as soon as I try this.

Edit: After edits, package runs, but does not report status - wonder what Synology changed there as well.

**Comment by colin1497** [comment]
Thanks.  I was going to update for 1.9 anyway, will test this and merge this in.

**Comment by OnTheMike** [comment]
Ran into this issue as well, did the change work and will it be included in the package?

**Comment by colin1497** [comment]
Circling back to this this morning.  Testing shortly.

I broke it first test.  Went ahead and published 1.9 update, and coming back to this.

**Comment by OnTheMike** [comment]
Great! As soon as it's ready I'll try it out..

On Tue, 22 Mar 2016 at 15:51 colin1497 notifications@github.com wrote:
Circling back to this this morning. Testing shortly.

**Comment by yulbeast** [comment]
I'm new to all this.
I got the same issue trying to install the package. Do I have to edit a file or that is an advise for the developer and I have to wait for a new version?

**Comment by ghost** [comment]
Hi 
I did modify the script according the reciepe in this post. But the server was unable to start successfully.

The log file gave me some hint. Apparently I had an old 1.8.9 world on the server which it tried to upgrade. This process usually takes longer than the startup script would allow. Shutting down the server prematurely. 

The workaround is to repeat starting the server until the world upgrade is done. Is there a way to fix this in the script?

**Comment by avluis** [comment]
@bogdanwilli Can I get a copy of your script, I can't get mine to work, lol (I'm supposed to be good at scripting, btw).
I can probably fix the upgrade wait timer though - moving that part out of the installation would be the right way to go.

**Comment by colin1497** [comment]
Geez, sorry for taking so long.  Finally got my rackstation to DSM 6.  I had previously tried the @nucky25 recommended patch but it had failed under DSM 5.2.  Now I have applied it in build 25 and I have it installing with this patch, but reporting "stopped" in the GUI.

You can test build 25 from my distro right now.

**Comment by colin1497** [comment]
Build 0026 works.  Manfred Stumpf had a simple change that fixed the status reporting issue.

**Comment by avluis** [comment]
@colin1497 Super awesome!!
This is unrelated, maybe I should open an issue for it or have @bogdanwilli who mentioned this open it, but do you think implementing a timer or similar help the startup script when the minecraft binary needs to upgrade the world, or was this already addressed?

**Comment by colin1497** [comment]
Timeout hasn't been addressed.  Also note, I created a Spigot install and that's what I'm running at my house now, not vanilla.
